# $JDTAUS$

name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      if: runner.os == 'Linux'
        sudo apt-get update
        sudo apt-get install -y libpq-dev libecpg-dev

    - name: Run make
      run: make
